version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html/community
hooks:
  ApplicationStart:
    - location: ./deploy-scripts/start.sh
  ValidateService:
    - location: ./deploy-scripts/verify.sh
      timeout: 1000
