version: 0.1
phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Pre_build started on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`