version: 0.2
phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Pre_build started on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'
  ## If you want to flaten the output (https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html)
  #base-directory: 'my-build*'
  #discard-paths: yes